### ISSUE TITLE
some quick reviews

### ISSUE THREAD

**Issue by bobzhang** [nebuta/bucklescript-todomvc-jquery#1]
1. it's not good checking in cm\* files, checking in js files are fine
2. some array functions are already in stdlib, contributions are welcome:
   for example `array_append` --> Js.Array.push (https://github.com/bloomberg/bucklescript/blob/master/jscomp/others/js_array.ml#L66)
3. you have more flexibility in naming here for external: 
   https://github.com/nebuta/bucklescript-todomvc-jquery/blob/master/bs/jquery.ml#L17
   maybe a more meaningful name help

**Comment by nebuta** [comment]
Thank you for the review. I missed Js.Array functions!

About point 3, jQuery uses the same method name for a setter and a getter. I am wondering what is a good way to give them a type in BuckleScript. Should I just use different names like `attr`, `attr_`, or should I use different algebraic data types to combine them for each method with the same name?

**Comment by bobzhang** [comment]
how about `attr`, `attr_set`

**Comment by nebuta** [comment]
That sounds good, I'll work to complete the binding to jQuery.
