### ISSUE TITLE
jquery.on signature is problematic

### ISSUE THREAD

**Issue by mpenet** [nebuta/bucklescript-todomvc-jquery#2]
Hi, 

I was trying to learn from this project and play with the code a bit, I noticed the signature of jQuery "on" seems wrong. 

it should be : 
`external on : string -> (jquery -> 'a Js.t -> Js.boolean [@bs.this]) -> jquery = "" [@@bs.send.pipe: jquery]` 
instead of 
`external on : string -> (jquery -> 'a Js.t -> bool [@bs.this]) -> jquery = "" [@@bs.send.pipe: jquery]` 

Notice the `Js.boolean` vs `bool`, otherwise the code emited will be `0` intead of `false`. This is ok in most case, but if you bind a submit handler and wish to prevent the submit, this will not work.

Cheers and thanks for the project, 

Max

**Comment by nebuta** [comment]
Hi Max,

Thank you for your comment. I changed them in https://github.com/nebuta/bucklescript-todomvc-jquery/commit/611d26dde629fb0f53c3bedda59db49b505d5445. I also noticed that bsc 1.0.3 gives warning for passing OCaml's `bool` to JS functions.

Nebuta
