### ISSUE TITLE
Global checkbox not working

### ISSUE THREAD

**Issue by alainfrisch** [nebuta/bucklescript-todomvc-jquery#3]
The checkbox to the left of the new entry field does not seem to work (it doesn't change the status of displayed entries).

**Comment by nebuta** [comment]
I can't reproduce this issue (Chrome, Firefox, Safari on Mac). Could you check this again with the latest commit https://github.com/nebuta/bucklescript-todomvc-jquery/commit/611d26dde629fb0f53c3bedda59db49b505d5445?

**Comment by alainfrisch** [comment]
I only tried the online demo ( http://nebuta.github.io/bs-todomvc/ ), with both Firefox and Chrome.   Perhaps it has been fixed in the development version already?

**Comment by nebuta** [comment]
Oh, I had misunderstood your comment. Implementation for "global checkbox" was totally missing, and I just added it in the latest update of this repo https://github.com/nebuta/bucklescript-todomvc-jquery/commit/8303956a1e862fa865f3a693ad34fc955f116159 as well as the online demo.
